### PR TITLE
Adds README

### LINKED ISSUE #429: Problem: Storage Service docs has no README.md or contributing.md
**Version of the documentation**
All

**Page (and section, if applicable) where the issue occurs**
Github repo

**Description of the issue**
There is no README or CONTRIBUTING file in the repo so if folks want to make suggestions/changes they may not know where to start. 

**Suggested fix**
With a couple of small changes the README from the am-docs would probably be fine, and it can also point to the am-docs wiki for contributing information.

### PR DESCRIPTION
**Pull request by ablwr**
Resolves https://github.com/archivematica/Issues/issues/429

### CODE REVIEW

**Review by ross-spencer — COMMENTED** [review]
This is looking good. As you said, some of this is from the am-docs as a base? It might be the case there too, we should probably keep an eye on:

* [Line length](https://github.com/artefactual/archivematica-docs/blob/12da09e3664025169450ac8b913639ff85ebba84/style_guide.md#formatting-and-punctuation)
* Abbreviations, where `doc` might be more helpful to some users as `documentation`. 

I didn't pick up on anything else. Great to have these issues coming off the rank, thanks @ablwr!

**Comment by ablwr** [comment]
Oh yeah, my editor flagged the line length but it was already like that for the archivematica-docs -- I can update both, along with your other suggestion!

**Comment by ablwr** [comment]
Updated and added the license, too! I also removed the Travis Build as passing or failing, because it was failing and pointing to the 1.8 docs. It seems if we have to keep updating the README every time we make a new release to point to the current branch, it's just another administrative task to remember to do and doesn't provide that much value overall. But open to other opinions.

**Review by ross-spencer — APPROVED** [review]
Have you adopted a partial semantic-line-break approach here? We don't normally adopt that, but this renders well and looks good to go otherwise. Thanks again.

**Comment by ablwr** [comment]
It was already like that! So I just added the line breaks where it broke the width rule, it was only intentional in the "change as little as possible" sense.

**Comment by ross-spencer** [comment]
Oh yep, that makes sense, I think we straddled both approaches for a bit.

**Comment by sromkey** [comment]
This looks great Ashley, thanks for doing this!

**Pull request merged**
